<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PBMS_WPF_Application.Core\PBMS_WPF_Application.Core.csproj" />
    <ProjectReference Include="..\PBMS_WPF_Application.DAL\PBMS_WPF_Application.DAL.csproj" />
  </ItemGroup>

</Project>
